change texhash search

diff --git a/pandoc/extras/install-tex-fonts b/pandoc/extras/install-tex-fonts
--- a/pandoc/extras/install-tex-fonts
+++ b/pandoc/extras/install-tex-fonts
@@ -93,16 +93,13 @@ else
     XZ_CMD=xz
 fi
 TEXHASH=texhash$EXT
-## We only consider commands from the installation directory defined by TEXLIVE_HOME
-## TEXHASH_CMD="$(command -v $TEXHASH)"
-## if ! [ -x "$TEXHASH_CMD" ]; then
-    case $OS in
-        Win) TEXHASH_CMD=$TEXLIVE_HOME/bin/win32/$TEXHASH ;;
-        Mac) TEXHASH_CMD=$TEXLIVE_HOME/bin/x86_64-darwin/$TEXHASH ;;
-        *)   TEXHASH_CMD=$TEXLIVE_HOME/bin/x86_64-linux/$TEXHASH
-    esac
-    [ -x "$TEXHASH_CMD" ] || { echo "Error: $TEXHASH executable not found (check variable TEXLIVE_HOME)" >>$LOG_FILE; exit 1; }
-## fi
+## We give priority to commands from the installation directory defined by TEXLIVE_HOME
+if [ -d "$TEXLIVE_HOME" ]; then
+    TEXHASH_CMD="$(find $TEXLIVE_HOME $TEXHASH)"
+else
+    TEXHASH_CMD="$(command -v $TEXHASH)"
+fi
+[ -x "$TEXHASH_CMD" ] || { echo "Error: $TEXHASH executable not found (check variable TEXLIVE_HOME)" >>$LOG_FILE; exit 1; }
 
 BASENAME="$(basename "$0")"
 DOWNLOADS_DIR=$PROG_HOME/downloads
